import type { FastifyInstance } from "fastify";
import { assetsRoutes } from "./assets.js";
import { bridgesRoutes } from "./bridges.js";
import { websocketRoutes } from "./websocket.js";
import { alertsRoutes } from "./alerts.routes.js";
import { exportsRoutes } from "./exports.js";
import { circuitBreakerRoutes } from "./circuitBreaker.js";
import { preferencesRoutes } from "./preferences.js";
import { apiKeysRoutes } from "./apiKeys.js";
import jobsRoutes from "./jobs.js";
import { webhooksRoutes } from "./webhooks.js";
import { configRoutes } from "./config.js";
import { aggregationRoutes } from "./aggregation.js";
import { metadataRoutes } from "./metadata.js";
import { analyticsRoutes } from "./analytics.js";
import { watchlistsRoutes } from "./watchlists.js";
import { cacheRoutes } from "./cache.js";
import { healthRoutes } from "./health.js";
import { rateLimitAdminRoutes } from "./rateLimitAdmin.js";
import { tracingAdminRoutes } from "./tracingAdmin.js";
import { validationAdminRoutes } from "./validationAdmin.js";
import { alertRoutingAdminRoutes } from "./alertRoutingAdmin.js";
import { metricsRoutes } from "./metrics.js";
import { priceFeedsRoutes } from "./priceFeeds.js";
import { supplyChainRoutes } from "./supplyChain.js";
import { transactionsRoutes } from "./transactions.js";
import { balanceRoutes } from "./balances.js";
import { poolRoutes } from "./pools.routes.js";
import { searchRoutes } from "./search.routes.js";
import { cleanupRoutes } from "./cleanup.routes.js";
import { discordRoutes } from "./discord.routes.js";
import { alertRulesRoutes } from "./alertRules.js";
import { auditRoutes } from "./audit.js";
import { bridgeRegistryRoutes } from "./bridge-registry.routes.js";
import { incidentRoutes } from "./incidents.routes.js";
import { healthScoreHistoryRoutes } from "./healthScoreHistory.routes.js";
import { horizonStreamRoutes } from "./horizonStream.routes.js";
import { adminRotationRoutes } from "./adminRotation.js";
import { digestSchedulerRoutes } from "./digestScheduler.js";
import { alertSuppressionRoutes } from "./alertSuppression.js";
import { externalDependenciesRoutes } from "./externalDependencies.routes.js";
import { providerHealthRegistryRoutes } from "./providerHealthRegistry.routes.js";
import { outboxAdminRoutes } from "./outbox-admin.js";
import { adminConfigRoutes } from "./admin/configs.js";

export async function registerRoutes(server: FastifyInstance) {
  server.register(assetsRoutes, { prefix: "/api/v1/assets" });
  server.register(bridgesRoutes, { prefix: "/api/v1/bridges" });
  server.register(websocketRoutes, { prefix: "/api/v1/ws" });
  server.register(alertsRoutes, { prefix: "/api/v1/alerts" });
  server.register(exportsRoutes, { prefix: "/api/v1/exports" });
  server.register(circuitBreakerRoutes, { prefix: "/api/v1/circuit-breaker" });
  server.register(preferencesRoutes, { prefix: "/api/v1/preferences" });
  server.register(apiKeysRoutes, { prefix: "/api/v1/admin/api-keys" });
  server.register(jobsRoutes, { prefix: "/api/v1/jobs" });
  server.register(webhooksRoutes, { prefix: "/api/v1/webhooks" });
  server.register(configRoutes, { prefix: "/api/v1/config" });
  server.register(aggregationRoutes, { prefix: "/api/v1/aggregation" });
  server.register(metadataRoutes, { prefix: "/api/v1/metadata" });
  server.register(analyticsRoutes, { prefix: "/api/v1/analytics" });
  server.register(watchlistsRoutes, { prefix: "/api/v1/watchlists" });
  server.register(cacheRoutes, { prefix: "/api/v1/cache" });
  server.register(healthRoutes, { prefix: "/api/v1/health" });
  // Backward-compatible health endpoints for load tests and probes
  server.register(healthRoutes, { prefix: "/health" });
  server.register(rateLimitAdminRoutes, { prefix: "/api/v1/admin/rate-limit" });
  server.register(tracingAdminRoutes, { prefix: "/api/v1/admin/tracing" });
  server.register(validationAdminRoutes, { prefix: "/api/v1/admin/validation" });
  server.register(alertRoutingAdminRoutes, { prefix: "/api/v1/admin/alert-routing" });
  server.register(metricsRoutes, { prefix: "/metrics" });
  server.register(priceFeedsRoutes, { prefix: "/api/v1/price-feeds" });
  server.register(supplyChainRoutes, { prefix: "/api/v1/supply-chain" });
  server.register(transactionsRoutes, { prefix: "/api/v1/transactions" });
  server.register(balanceRoutes, { prefix: "/api/v1/balances" });
  server.register(poolRoutes, { prefix: "/api/v1/pools" });
  server.register(searchRoutes, { prefix: "/api/v1/search" });
  server.register(cleanupRoutes, { prefix: "/api/v1/cleanup" });
  server.register(discordRoutes, { prefix: "/api/v1/discord" });
  server.register(alertRulesRoutes, { prefix: "/api/v1/alert-rules" });
  server.register(auditRoutes, { prefix: "/api/v1/admin/audit" });
  server.register(bridgeRegistryRoutes, { prefix: "/api/v1/bridge-registry" });
  server.register(incidentRoutes, { prefix: "/api/v1/incidents" });
  server.register(healthScoreHistoryRoutes, { prefix: "/api/v1/health-score-history" });
  server.register(horizonStreamRoutes, { prefix: "/api/v1/horizon-streams" });
  server.register(adminRotationRoutes, { prefix: "/api/v1/admin/rotation" });
  server.register(digestSchedulerRoutes, { prefix: "/api/v1/digest" });
  server.register(alertSuppressionRoutes, { prefix: "/api/v1/alert-suppression" });
  server.register(externalDependenciesRoutes, { prefix: "/api/v1/external-dependencies" });
  server.register(providerHealthRegistryRoutes, { prefix: "/api/v1/providers/health" });
  server.register(outboxAdminRoutes, { prefix: "/api/v1/admin/outbox" });
  server.register(adminConfigRoutes, { prefix: "/api/v1/admin/configs" });
}
